export const ROUTES = {
  HOME: '/',
  DESIGN_SYSTEM: '/design-system',
  HELP_CENTER: '/help-center',
  NOTIFICATIONS: '/notifications',
  AUTH: {
    LOGIN: '/login',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password/:token',
    VERIFY_EMAIL: '/verify-email/:token',
    UNAUTHORIZED: '/unauthorized',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    INSIGHTS: '/admin/insights',
    ALERTS: '/admin/alerts',
    EMPLOYEES: '/admin/employees',
    ATTENDANCE: '/admin/attendance',
    LEAVES: '/admin/leaves',
    PAYROLL: '/admin/payroll',
    DOCUMENTS: '/admin/documents',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
  },
  EMPLOYEE: {
    DASHBOARD: '/employee/dashboard',
    PROFILE: '/employee/profile',
    ATTENDANCE: '/employee/attendance',
    LEAVES: '/employee/leaves',
    PAYROLL: '/employee/payroll',
    DOCUMENTS: '/employee/documents',
    HELP_CENTER: '/employee/help-center',
  },
};
